ebookdemo/author/urls.py
from django.urls import path
from .views import AuthorView

app_name='author'
urlpatterns = [
    path('<slug:author_slug>', AuthorView.as_view(), name='author_by_slug'),
]

ebookdemo/book/urls.py
from django.urls import path
from .views import SaveComment, SaveChildComment, BookRankings, SaveLike, FavouriteBooks, AddFavourite, BooksSearch, BooksNew, SubmitRating, ShareBook
from .views import check_like_book, add_comment, get_comments, check_favourite_book
app_name = 'book'
urlpatterns = [
    path('save_comment', SaveComment.as_view(), name='save_comment'),
    path('save_child_comment', SaveChildComment.as_view(), name='save_child_comment'),
    path('ranking', BookRankings.as_view(), name='ranking'),
    path('favourite', FavouriteBooks.as_view(), name='favourite'),
    path('like/<int:book_id>/', SaveLike.as_view(), name='like_book'),
    path('check_like_book/<int:book_id>/', check_like_book, name='check_like_book'),
    path('add-comment/<int:book_id>/', add_comment, name='add-comment'),
    path('get-comments/<int:book_id>/', get_comments, name='get-comments'),
    path('check_favourite_book/<int:book_id>/', check_favourite_book, name='check_favourite_book'),
    path('add_favourite/<int:book_id>/', AddFavourite.as_view(), name='add_favourite'),
    path('search', BooksSearch.as_view(), name='search'),
    path('booksnew/<int:page>/', BooksNew.as_view(), name='booksnew'),
    path('submit_rating/<int:book_id>/', SubmitRating.as_view(), name='submit_rating'),
    path('share_book', ShareBook.as_view(), name='shareBook'),
]

ebookdemo/chapter/urls.py
from django.urls import path
from .views import ChapterView, ReadingHistoryView

app_name = 'chapter'
urlpatterns = [
    path('<slug:book_slug>/<slug:chapter_slug>', ChapterView.as_view(), name='chapter_by_slug'),
    path('reading_history', ReadingHistoryView.as_view(), name='reading_history'),
]

ebookdemo/core/urls.py
from django.urls import path
from .views import HomeView,Detail, DownloadPDFView, PredictView, TrainData

app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('detail/<slug:book_slug>', Detail.as_view(), name='detail'),
    path('download-pdf/<int:book_id>/', DownloadPDFView.as_view(), name='download_pdf'),
    path('chatbot/predict', PredictView.as_view(), name="predict"),
    path('chatbot/training', TrainData.as_view(), name="training"),
]

ebookdemo/ebook/urls.py
from django.contrib import admin
from django.urls import path, include

#hỗ trợ upload file
from django.conf.urls.static import static
from django.conf import settings
# ---

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('genre/', include('genre.urls')),
    path('chapter/', include('chapter.urls')),
    path('user/', include('user.urls')),
    path('author/', include('author.urls')),
    path('book/', include('book.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''path('genre/', include('genre.urls')),
    
    path('chapter/', include('chapter.urls')),'''

ebookdemo/genre/urls.py
from django.urls import path
from .views import GenreView

app_name='genre'
urlpatterns = [
    path('<slug:genre_slug>', GenreView.as_view(), name='genre_by_slug'),
]

ebookdemo/user/urls.py
from django.urls import path
from .views import LoginView, RegisterView, LogoutView, AccountView, ChangePassword

app_name = 'user'
urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('account', AccountView.as_view(), name='account'),
    path('change-password', ChangePassword.as_view(), name='change-password'),
]

ebookdemo/author/models.py
from django.db import models

# Create your models here.

ebookdemo/author/models/models.py
from django.db import models
from django.utils import timezone
from genre.models.models import Genre

class Author(models.Model):
    author_name = models.CharField(max_length=255, null=False, blank=False)
    author_slug = models.CharField(max_length=100, null=False, blank=False, unique=True)
    create_at = models.DateTimeField(auto_now_add=timezone.datetime.now())
    
    def __str__(self):
        return self.author_name

ebookdemo/chapter/models.py
from django.db import models

# Create your models here.

ebookdemo/chapter/models/models.py
from django.db import models
from django.utils import timezone
from book.models.models import Book
from user.models.models import MyUser

# Create your models here.
class Chapter(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    chapter_name = models.CharField(max_length=255, null=True, blank=False, unique=True)
    chapter_content = models.TextField(null=False, blank=False)
    chapter_slug = models.CharField(max_length=100, null=False, blank=False, unique=True)
    create_at = models.DateTimeField(auto_now_add=timezone.datetime.now())
    update_at = models.DateTimeField(auto_now=timezone.datetime.now())

    def __str__(self):
        return f'{self.book.book_name} - {self.chapter_name}'

class ReadingHistory(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=timezone.datetime.now())
    update_at = models.DateTimeField(auto_now=timezone.datetime.now())

    def __str__(self):
        return f'{self.user.username} - {self.chapter.book.book_name} - {self.chapter.chapter_name}'


class NotificationChapter(models.Model): #Thông báo khi có chương mới
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    notification_content = models.CharField(max_length=255, null=True)
    create_at = models.DateTimeField(auto_now_add=timezone.datetime.now())
    update_at = models.DateTimeField(auto_now=timezone.datetime.now())

    def __str__(self):
        return f'{self.chapter.book.book_name} - {self.chapter.chapter_name} - {self.notification_content}'

ebookdemo/genre/models.py
from django.db import models

# Create your models here.

ebookdemo/genre/models/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Genre(models.Model):
    genre_name = models.CharField(max_length=100, default='', unique=True)
    genre_description = models.CharField(max_length=255, default='')
    genre_slug = models.CharField(max_length=100, default='', unique=True)
    create_at = models.DateTimeField(auto_now_add=timezone.datetime.now())
    update_at = models.DateTimeField(auto_now=timezone.datetime.now())
    def __str__(self):
        return self.genre_name

ebookdemo/author/views.py
from django.shortcuts import render
from django.views import View
from book.models.models import Book
from author.models.models import Author


# Create your views here.
class AuthorView(View):
    def get(self, request, author_slug):
        books = Book.objects.filter(author__author_slug = author_slug)
        context = {'books':books}
        return render(request, 'homepage/author.html', context)

ebookdemo/chapter/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from .models.models import Chapter, ReadingHistory
from book.models.models import Book
from user.models.models import MyUser
from train.recommendation import Recommendation
import pickle
import pandas as pd
# Create your views here.
class ChapterView(View):
    def get(self,request,book_slug,chapter_slug):
        book = Book.objects.get(book_slug = book_slug)
        chapter = Chapter.objects.filter(book__book_slug=book_slug, chapter_slug=chapter_slug)[0]
        contents = chapter.chapter_content.split('.')
        chapters = Chapter.objects.filter(book__book_slug=book_slug)

        Recommendation.get_recommendations(book.book_name)
        print('Sach hien tai : '+book.book_name)
        # Lay ds sach duoc de xuat
        list_book = pickle.load(open('./train/books.pkl', 'rb'))
        list_book = pd.DataFrame(list_book)
        list_book_id = [] # mang chua danh sach de xuat
        for idx in list_book.index:
            #print(list_book['book_id'][idx])
            list_book_id.append(list_book['id'][idx])

        book_recommendation= []
        for idx in list_book_id:
            print(idx)
            book_recom  = Book.objects.get(pk = idx)
            book_recommendation.append(book_recom)
            print(book_recom.book_name)

        user_id = request.session['id']
        if user_id > 0:
            user = MyUser.objects.get(pk=user_id)
            try:
                reading = ReadingHistory.objects.get(user=user, chapter__book=book)
                reading.chapter = chapter
                reading.save()
            except ReadingHistory.DoesNotExist:
                ReadingHistory.objects.create(user=user, chapter=chapter)

        context = {'chapter': chapter, 'contents': contents, 'chapters':chapters, 'book':book,'book_recommendation':book_recommendation}
        return render(request, 'homepage/chapter.html', context)

class ReadingHistoryView(View):
    def get(self, request):
        user_id = request.session['id']
        user = MyUser.objects.get(pk=user_id)
        reading_books = ReadingHistory.objects.filter(user=user).order_by('-create_at')
        context = {'reading_books':reading_books, 'title':'Lịch sử đọc'}
        return render(request, 'homepage/reading_history.html', context)

ebookdemo/genre/views.py
from django.shortcuts import render
from django.views import View
from book.models.models import Book
from genre.models.models import Genre

# Create your views here.
class GenreView(View):
    def get(self, request, genre_slug):
        books = Book.objects.filter(genre__genre_slug = genre_slug)
        context = {'books':books}
        return render(request, 'homepage/genre.html', context)

ebookdemo/templates/homepage/account.html
{% extends 'homepage/base.html' %}
{% block content %}
{% load static %}      
      <div class="container">
         <div class="row fullwith-slider"></div>
      </div>
      <div class="container">
         <div class="row container" id="wrapper">
            <div class="halim-panel-filter">
               <div id="ajax-filter" class="panel-collapse collapse" aria-expanded="true" role="menu">
                  <div class="ajax"></div>
               </div>
            </div>
            <div class="section-bar clearfix">
               <h2 class="section-title"><span style="color:#ffed4d">Thông tin tài khoản</span></h2>
            </div>
            <div class="col-xs-12 carausel-sliderWidget">
               <section id="halim-advanced-widget-4">
                  <div class="entry-content htmlwrap clearfix">
                     <div class="video-item halim-entry-box" style="margin:30px 100px">
                  <form id="register-form" action="{% url 'user:account' %}" method="post" role="form">
                     {% if error_message_2 %}
                              <span class='text-success'>{{error_message_2}}</span>
                     {% endif %}
                     {% csrf_token %}
                     <div class="form-group">
                        
                                  {{f.email}}
                     </div>
                     <div class="form-group">
               
                           {{f.first_name}}
                     </div>
                     <div class="form-group">
               
                           {{f.last_name}}
                     </div>
                     <div class="form-group">

                           {{f.sex}}
                     </div>
                     <div class="form-group">
                           <label for="birthday">Ngày sinh:</label>
                           
                           {{f.birth}}
                     </div>
                     <div class="form-group">
               
                           {{f.address}}
                     </div>
                     
                     <div class="form-group">
                        <div class="row">
                           <div class="col-sm-6 col-sm-offset-3">
                              <input type="submit" name="update-account" tabindex="4" class="form-control btn btn-register" value="Cập nhật">
                              <a href="{% url 'user:change-password' %}" style="margin-top:5px" type="button" tabindex="4" class="form-control btn btn-register">Đổi mật khẩu</a>
                           </div>
                           
                        </div>
                     </div>
                  </form>
                  <div>
                  </div>
               </section>
               <div class="clearfix"></div>
            </div>
            
         </div>
      </div>
      <div class="clearfix"></div>

{% endblock content %}

ebookdemo/templates/homepage/base_login.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-6">
								<a href="#" class="active" id="login-form-link">Login</a>
							</div>
							<div class="col-xs-6">
								<a href="#" id="register-form-link">Register</a>
							</div>
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">
                                
								<form id="login-form" action="{% url 'user:login' %}" method="post" role="form" style="display: block;">
                                    {% if error_message %}
                                    <span class='text-danger'>{{error_message}}</span>
                                    {% endif %}
									{% csrf_token %}
                                    <div class="form-group">
										<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="{{username}}">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
									</div>
									<div class="form-group text-center">
										<input type="checkbox" tabindex="3" class="" name="remember" id="remember">
										<label for="remember"> Remember Me</label>
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-lg-12">
												<div class="text-center">
													<a href="https://phpoll.com/recover" tabindex="5" class="forgot-password">Forgot Password?</a>
												</div>
											</div>
										</div>
									</div>
								</form>
								<form id="register-form" action="{% url 'user:register' %}" method="post" role="form" style="display: none;">
									{% if error_message_2 %}
                                    <span class='text-success'>{{error_message_2}}</span>
                                    {% endif %}
                                    {% csrf_token %}
                                    <div class="form-group">
										{% comment %} <input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value=""> {% endcomment %}
                                        {{f.username}}
									</div>
									<div class="form-group">
										{% comment %} <input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email Address" value=""> {% endcomment %}
                                        {{f.email}}
									</div>
                                    <div class="form-group">
										{% comment %} <input type="text" name="first_name" id="first_name" tabindex="1" class="form-control" placeholder="First Name" value=""> {% endcomment %}
                                        {{f.first_name}}
                                    </div>
                                    <div class="form-group">
										{% comment %} <input type="text" name="last_name" id="last_name" tabindex="1" class="form-control" placeholder="Last Name" value=""> {% endcomment %}
                                        {{f.last_name}}
                                    </div>
                                    <div class="form-group">
    
                                        {{f.sex}}
                                    </div>
                                    <div class="form-group">
                                        <label for="birthday">Ngày sinh:</label>
                                        {% comment %} <input type="date" id="birthday" name="birthday"> {% endcomment %}
                                        {{f.birth}}
                                    </div>
                                    <div class="form-group">
										{% comment %} <input type="text" name="address" id="address" tabindex="1" class="form-control" placeholder="Address" value=""> {% endcomment %}
                                        {{f.address}}
									</div>
									<div class="form-group">
										{% comment %} <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password"> {% endcomment %}
                                        {{f.password}}
                                    </div>
									<div class="form-group">
										<input type="password" name="confirm-password" id="confirm-password" tabindex="2" class="form-control" placeholder="Confirm Password">
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Register Now">
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
    <style>
        body {
            padding-top: 90px;
        }
        .panel-login {
            border-color: #ccc;
            -webkit-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);
            -moz-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);
            box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);
        }
        .panel-login>.panel-heading {
            color: #00415d;
            background-color: #fff;
            border-color: #fff;
            text-align:center;
        }
        .panel-login>.panel-heading a{
            text-decoration: none;
            color: #666;
            font-weight: bold;
            font-size: 15px;
            -webkit-transition: all 0.1s linear;
            -moz-transition: all 0.1s linear;
            transition: all 0.1s linear;
        }
        .panel-login>.panel-heading a.active{
            color: #029f5b;
            font-size: 18px;
        }
        .panel-login>.panel-heading hr{
            margin-top: 10px;
            margin-bottom: 0px;
            clear: both;
            border: 0;
            height: 1px;
            background-image: -webkit-linear-gradient(left,rgba(0, 0, 0, 0),rgba(0, 0, 0, 0.15),rgba(0, 0, 0, 0));
            background-image: -moz-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));
            background-image: -ms-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));
            background-image: -o-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));
        }
        .panel-login input[type="text"],.panel-login input[type="email"],.panel-login input[type="password"] {
            height: 45px;
            border: 1px solid #ddd;
            font-size: 16px;
            -webkit-transition: all 0.1s linear;
            -moz-transition: all 0.1s linear;
            transition: all 0.1s linear;
        }
        .panel-login input:hover,
        .panel-login input:focus {
            outline:none;
            -webkit-box-shadow: none;
            -moz-box-shadow: none;
            box-shadow: none;
            border-color: #ccc;
        }
        .btn-login {
            background-color: #59B2E0;
            outline: none;
            color: #fff;
            font-size: 14px;
            height: auto;
            font-weight: normal;
            padding: 14px 0;
            text-transform: uppercase;
            border-color: #59B2E6;
        }
        .btn-login:hover,
        .btn-login:focus {
            color: #fff;
            background-color: #53A3CD;
            border-color: #53A3CD;
        }
        .forgot-password {
            text-decoration: underline;
            color: #888;
        }
        .forgot-password:hover,
        .forgot-password:focus {
            text-decoration: underline;
            color: #666;
        }
        
        .btn-register {
            background-color: #1CB94E;
            outline: none;
            color: #fff;
            font-size: 14px;
            height: auto;
            font-weight: normal;
            padding: 14px 0;
            text-transform: uppercase;
            border-color: #1CB94A;
        }
        .btn-register:hover,
        .btn-register:focus {
            color: #fff;
            background-color: #1CA347;
            border-color: #1CA347;
        }

        {% comment %} Radio {% endcomment %}
        .radio-container {
            display: flex;
            flex-direction: column;
        }
        
        .radio-label {
            position: relative;
            padding-left: 30px;
            margin-bottom: 10px;
            cursor: pointer;
            font-size: 14px;
        }
        
        .radio-input {
            position: absolute;
            opacity: 0;
            cursor: pointer;
        }
        
        .radio-custom {
            position: absolute;
            top: 0;
            left: 0;
            height: 20px;
            width: 20px;
            background-color: #fff;
            border: 2px solid #007bff;
            border-radius: 50%;
        }
        
        .radio-input:checked + .radio-custom::before {
            content: "";
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 12px;
            height: 12px;
            background-color: #007bff;
            border-radius: 50%;
        }
        /* Loại bỏ mặc định của input date và sử dụng màu chữ đen */
        input[type="date"] {
            appearance: none;
            -webkit-appearance: none;
            border: 1px solid #ccc;
            padding: 5px;
            font-size: 16px;
        }

        /* Thay đổi màu nền khi input có focus */
        input[type="date"]:focus {
            background-color: #f0f0f0;
            outline: none;
        }
    </style>
    <script>
        $(function() {

            $('#login-form-link').click(function(e) {
                $("#login-form").delay(100).fadeIn(100);
                 $("#register-form").fadeOut(100);
                $('#register-form-link').removeClass('active');
                $(this).addClass('active');
                e.preventDefault();
            });
            $('#register-form-link').click(function(e) {
                $("#register-form").delay(100).fadeIn(100);
                 $("#login-form").fadeOut(100);
                $('#login-form-link').removeClass('active');
                $(this).addClass('active');
                e.preventDefault();
            });
        
        });
    </script>

ebookdemo/templates/homepage/comment_list.html
<!-- comments/comment_list.html -->
{% for comment in comments %}
<div class="comment">
    <p>{{ comment.user.username }}</p>
    <p>{{ comment.created_at }}</p>
    <p>{{ comment.content }}</p>
</div>
{% endfor %}

ebookdemo/templates/homepage/navbar.html
{% load static %}
<header id="header">
    <div class="container">
       <div class="row" id="headwrap">
          <div class="col-md-3 col-sm-6 slogan">
             
               <img style="weight:70px;height:70px;" src="{% static 'logo.png' %}" alt="My image">
             </a>
             
          </div>
          <div class="col-md-5 col-sm-6 halim-search-form hidden-xs">
             <div class="header-nav">
                <div class="col-xs-12">
                   <form id="search-form-pc" name="halimForm" role="search" action="{% url 'book:search' %}" method="GET">
                      <div class="form-group">
                         <div class="input-group col-xs-12">
                            <input id="search" type="text" name="keywords" class="form-control" placeholder="Tìm kiếm..." autocomplete="off" required>
                            <i class="animate-spin hl-spin4 hidden"></i>
                         </div>
                      </div>
                   </form>
                   <ul class="ui-autocomplete ajax-results hidden"></ul>
                </div>
             </div>
          </div>
          <div class="col-md-4 hidden-xs">
            <div id="get-bookmark" class="box-shadow">
               <i class="hl-bookmark"></i>
               <span> Bookmarks</span><span class="count">0</span>
               {% if request.session.username %}
                  <a href="{% url 'user:account' %}">{{request.session.username}}<a> <span> | <span>
                  <a href="{% url 'user:logout' %}">Logout<a>
               {% else %}
                  <a href="{% url 'user:login' %}">Login<a>
               {% endif %}
               
            </div>
             <div id="bookmark-list" class="hidden bookmark-list-on-pc">
                <ul style="margin: 0;"></ul>
             </div>
          </div>
       </div>
    </div>
 </header>
 
 <div class="navbar-container">
    <div class="container">
       <nav class="navbar halim-navbar main-navigation" role="navigation" data-dropdown-hover="1">
          <div class="navbar-header">
             <button type="button" class="navbar-toggle collapsed pull-left" data-toggle="collapse" data-target="#halim" aria-expanded="false">
             <span class="sr-only">Menu</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             </button>
             <button type="button" class="navbar-toggle collapsed pull-right expand-search-form" data-toggle="collapse" data-target="#search-form" aria-expanded="false">
             <span class="hl-search" aria-hidden="true"></span>
             </button>
             <button type="button" class="navbar-toggle collapsed pull-right get-bookmark-on-mobile">
             Bookmarks<i class="hl-bookmark" aria-hidden="true"></i>
             <span class="count">0</span>
             </button>
             <button type="button" class="navbar-toggle collapsed pull-right get-locphim-on-mobile">
             <a href="javascript:;" id="expand-ajax-filter" style="color: #ffed4d;">Lọc <i class="fas fa-filter"></i></a>
             </button>
          </div>
          <div class="collapse navbar-collapse" id="halim">
             <div class="menu-menu_1-container">
                <ul id="menu-menu_1" class="nav navbar-nav navbar-left">
                   <li class="current-menu-item active"><a title="Trang Chủ" href="{% url "core:index" %}">Trang Chủ</a></li>
                   <li class="mega"><a title="Books New" href="{% url 'book:booksnew' page=1%}">Sách mới nhất</a></li>
                   <li class="mega"><a title="Ranking" href="{% url "book:ranking" %}">Bảng xếp hạng</a></li>
                   <li class="mega"><a title="FavouriteBook" href="{% url "book:favourite" %}">Sách đánh dấu</a></li>
                   <li class="mega"><a title="Reading History" href="{% url "chapter:reading_history" %}">Lịch sử đọc</a></li>
                   <li class="mega dropdown">
                      <a title="Thể Loại" href="#" data-toggle="dropdown" class="dropdown-toggle" aria-haspopup="true">Thể Loại <span class="caret"></span></a>
                      <ul role="menu" class=" dropdown-menu">
                        {% for gr in genres_list %}
                         <li><a title="{{gr.genre_name}}" href="{% url "genre:genre_by_slug" gr.genre_slug%}">{{gr.genre_name}}</a></li>
                        {% endfor %}
                      </ul>
                   </li>
                </ul>
             </div>
             <ul class="nav navbar-nav navbar-left" style="background:#000;">
                <li><a href="#" onclick="locphim()" style="color: #ffed4d;">Lọc Sách</a></li>
             </ul>
             
            <ul class="nav navbar-nav navbar-right" style="background:#000;">
               <a class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Thông báo
               <span class="caret"></span></a>
               <ul class="dropdown-menu">
                  {% for notification in notifications_user %}
                 <li><a href="{% url 'chapter:chapter_by_slug' notification.chapter.book.book_slug notification.chapter.chapter_slug %}">{{notification.notification_content}}</a></li>
                 {% endfor %}
               </ul>
            </ul>
            
         </div>
       </nav>
       <div class="collapse navbar-collapse" id="search-form">
          <div id="mobile-search-form" class="halim-search-form"></div>
       </div>
       <div class="collapse navbar-collapse" id="user-info">
          <div id="mobile-user-login"></div>
       </div>
    </div>
 </div>
 </div>